<?php

use Illuminate\Database\Seeder;
use Shopbox\Models\Zpanel\Currency;
class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = collect([['name' => 'Euro (EUR)', 'iso_code' => 'EUR' ],
                                ['name' => 'United Kingdom Pounds (GBP)', 'iso_code' => 'GBP' ],
                                ['name' => 'Canadian Dollars (CAD)', 'iso_code' => 'CAD' ],
                                ['name' => 'Afghan Afghani (AFN)', 'iso_code' => 'AFN'],
                                ['name' => 'Albanian Lek (ALL)', 'iso_code' => 'ALL'],
                                ['name' => 'Algerian Dinar (DZD)', 'iso_code' => 'DZD'],
                                ['name' => 'Angolan Kwanza (AOA)', 'iso_code' => 'AOA'],
                                ['name' => 'Argentine Pesos (ARS)', 'iso_code' => 'ARS'],
                                ['name' => 'Armenian Dram (AMD)', 'iso_code' => 'AMD'],
                                ['name' => 'Aruban Florin (AWG)', 'iso_code' => 'AWG'],
                                ['name' => 'Australian Dollars (AUD)', 'iso_code' => 'AUD'],
                                ['name' => 'Barbadian Dollar (BBD)', 'iso_code' => 'BBD'],
                                ['name' => 'Azerbaijani Manat (AZN)', 'iso_code' => 'AZN'],
                                ['name' => 'Bangladesh Taka (BDT)', 'iso_code' => 'BDT'],
                                ['name' => 'Bahamian Dollar (BSD)', 'iso_code' => 'BSD'],
                                ['name' => 'Bahraini Dinar (BHD)', 'iso_code' => 'BHD'],
                                ['name' => 'Belarusian Ruble (BYR)', 'iso_code' => 'BYR'],
                                ['name' => 'Belize Dollar (BZD)', 'iso_code' => 'BZD'],
                                ['name' => 'Bhutanese Ngultrum (BTN)', 'iso_code' => 'BTN'],
                                ['name' => 'Bosnia and Herzegovina Convertible Mark (BAM)', 'iso_code' => 'BAM'],
                                ['name' => 'Brazilian Real (BRL)', 'iso_code' => 'BRL'],
                                ['name' => 'Bolivian Boliviano (BOB)', 'iso_code' => 'BOB'],
                                ['name' => 'Botswana Pula (BWP)', 'iso_code' => 'BWP'],
                                ['name' => 'Brunei Dollar (BND)', 'iso_code' => 'BND'],
                                ['name' => 'Bulgarian Lev (BGN)', 'iso_code' => 'BGN'],
                                ['name' => 'Burmese Kyat (MMK)', 'iso_code' => 'MMK'],
                                ['name' => 'Cambodian Riel', 'iso_code' => 'KHR'],
                                ['name' => 'Cape Verdean escudo (CVE)', 'iso_code' => 'CVE'],
                                ['name' => 'Cayman Dollars (KYD)', 'iso_code' => 'KYD'],
                                ['name' => 'Central African CFA Franc (XAF)', 'iso_code' => 'XAF'],
                                ['name' => 'Chilean Peso (CLP)', 'iso_code' => 'CLP'],
                                ['name' => 'Chinese Yuan Renminbi (CNY)', 'iso_code' => 'CNY'],
                                ['name' => 'Colombian Peso (COP)', 'iso_code' => 'COP'],
                                ['name' => 'Comorian Franc (KMF)', 'iso_code' => 'KMF'],
                                ['name' => 'Congolese franc (CDF)', 'iso_code' => 'CDF'],
                                ['name' => 'Costa Rican Colones (CRC)', 'iso_code' => 'CRC'],
                                ['name' => 'Croatian Kuna (HRK)', 'iso_code' => 'HRK'],
                                ['name' => 'Czech Koruny (CZK)', 'iso_code' => 'CZK'],
                                ['name' => 'Danish Kroner (DKK)', 'iso_code' => 'DKK'],
                                ['name' => 'Dominican Peso (DOP)', 'iso_code' => 'DOP'],
                                ['name' => 'East Caribbean Dollar (XCD)', 'iso_code' => 'XCD'],
                                ['name' => 'Egyptian Pound (EGP)', 'iso_code' => 'EGP'],
                                ['name' => 'Ethiopian Birr (ETB)', 'iso_code' => 'ETB'],
                                ['name' => 'CFP Franc (XPF)', 'iso_code' => 'XPF'],
                                ['name' => 'Fijian Dollars (FJD)', 'iso_code' => 'FJD'],
                                ['name' => 'Gambian Dalasi (GMD)', 'iso_code' => 'GMD'],
                                ['name' => 'Ghanaian Cedi (GHS)', 'iso_code' => 'GHS'],
                                ['name' => 'Guatemalan Quetzal (GTQ)', 'iso_code' => 'GTQ'],
                                ['name' => 'Guyanese Dollar (GYD)', 'iso_code' => 'GYD'],
                                ['name' => 'Georgian Lari (GEL)', 'iso_code' => 'GEL'],
                                ['name' => 'Haitian Gourde (HTG)', 'iso_code' => 'HTG'],
                                ['name' => 'Honduran Lempira (HNL)', 'iso_code' => 'HNL'],
                                ['name' => 'Hong Kong Dollars (HKD)', 'iso_code' => 'HKD'],
                                ['name' => 'Hungarian Forint (HUF)', 'iso_code' => 'HUF'],
                                ['name' => 'Icelandic Kronur (ISK)', 'iso_code' => 'ISK'],
                                ['name' => 'Indian Rupees (INR)', 'iso_code' => 'INR'],
                                ['name' => 'Indonesian Rupiah (IDR)', 'iso_code' => 'IDR'],
                                ['name' => 'Israeli New Shekel (NIS)', 'iso_code' => 'ILS'],
                                ['name' => 'Jamaican Dollars (JMD)', 'iso_code' => 'JMD'],
                                ['name' => 'Japanese Yen (JPY)', 'iso_code' => 'JPY'],
                                ['name' => 'Jersey Pound', 'iso_code' => 'JEP'],
                                ['name' => 'Jordanian Dinar (JOD)', 'iso_code' => 'JOD'],
                                ['name' => 'Kazakhstani Tenge (KZT)', 'iso_code' => 'KZT'],
                                ['name' => 'Kenyan Shilling (KES)', 'iso_code' => 'KES'],
                                ['name' => 'Kuwaiti Dinar (KWD)', 'iso_code' => 'KWD'],
                                ['name' => 'Kyrgyzstani Som (KGS)', 'iso_code' => 'KGS'],
                                ['name' => 'Laotian Kip (LAK)', 'iso_code' => 'LAK'],
                                ['name' => 'Latvian Lati (LVL)', 'iso_code' => 'LVL'],
                                ['name' => 'Lebanese Pounds (LBP)', 'iso_code' => 'LBP'],
                                ['name' => 'Lesotho Loti (LSL)', 'iso_code' => 'LSL'],
                                ['name' => 'Liberian Dollar (LRD)', 'iso_code' => 'LRD'],
                                ['name' => 'Malagasy Ariary (MGA)', 'iso_code' => 'MGA'],
                                ['name' => 'Macedonia Denar (MKD)', 'iso_code' => 'MKD'],
                                ['name' => 'Macanese Pataca (MOP)', 'iso_code' => 'MOP'],
                                ['name' => 'Malawian Kwacha (MWK)', 'iso_code' => 'MWK'],
                                ['name' => 'Maldivian Rufiyaa (MVR)', 'iso_code' => 'MVR'],
                                ['name' => 'Mexican Pesos (MXN)', 'iso_code' => 'MXN'],
                                ['name' => 'Malaysian Ringgits (MYR)', 'iso_code' => 'MYR'],
                                ['name' => 'Mauritian Rupee (MUR)', 'iso_code' => 'MUR'],
                                ['name' => 'Moldovan Leu (MDL)', 'iso_code' => 'MDL'],
                                ['name' => 'Moroccan Dirham', 'iso_code' => 'MAD'],
                                ['name' => 'Mongolian Tugrik', 'iso_code' => 'MNT'],
                                ['name' => 'Mozambican Metical', 'iso_code' => 'MZN'],
                                ['name' => 'Namibian Dollar', 'iso_code' => 'NAD'],
                                ['name' => 'Nepalese Rupee (NPR)', 'iso_code' => 'NPR'],
                                ['name' => 'Netherlands Antillean Guilder', 'iso_code' => 'ANG'],
                                ['name' => 'New Zealand Dollars (NZD)', 'iso_code' => 'NZD'],
                                ['name' => 'Nicaraguan Córdoba (NIO)', 'iso_code' => 'NIO'],
                                ['name' => 'Nigerian Naira (NGN)', 'iso_code' => 'NGN'],
                                ['name' => 'Norwegian Kroner (NOK)', 'iso_code' => 'NOK'],
                                ['name' => 'Omani Rial (OMR)', 'iso_code' => 'OMR'],
                                ['name' => 'Pakistani Rupee (PKR)', 'iso_code' => 'PKR'],
                                ['name' => 'Papua New Guinean Kina (PGK)', 'iso_code' => 'PGK'],
                                ['name' => 'Paraguayan Guarani (PYG)', 'iso_code' => 'PYG'],
                                ['name' => 'Peruvian Nuevo Sol (PEN)', 'iso_code' => 'PEN'],
                                ['name' => 'Philippine Peso (PHP)', 'iso_code' => 'PHP'],
                                ['name' => 'Polish Zlotych (PLN)', 'iso_code' => 'PLN'],
                                ['name' => 'Qatari Rial (QAR)', 'iso_code' => 'QAR'],
                                ['name' => 'Romanian Lei (RON)', 'iso_code' => 'RON'],
                                ['name' => 'Russian Rubles (RUB)', 'iso_code' => 'RUB'],
                                ['name' => 'Rwandan Franc (RWF)', 'iso_code' => 'RWF'],
                                ['name' => 'Samoan Tala (WST)', 'iso_code' => 'WST'],
                                ['name' => 'Saudi Riyal (SAR)', 'iso_code' => 'SAR'],
                                ['name' => 'Sao Tome And Principe Dobra (STD)', 'iso_code' => 'STD'],
                                ['name' => 'Serbian dinar (RSD)', 'iso_code' => 'RSD'],
                                ['name' => 'Seychellois Rupee (SCR)', 'iso_code' => 'SCR'],
                                ['name' => 'Singapore Dollars (SGD)', 'iso_code' => 'SGD'],
                                ['name' => 'Sudanese Pound (SDG)', 'iso_code' => 'SDG'],
                                ['name' => 'Syrian Pound (SYP)', 'iso_code' => 'SYP'],
                                ['name' => 'South African Rand (ZAR)', 'iso_code' => 'ZAR'],
                                ['name' => 'South Korean Won (KRW)', 'iso_code' => 'KRW'],
                                ['name' => 'South Sudanese Pound (SSP)', 'iso_code' => 'SSP'],
                                ['name' => 'Solomon Islands Dollar (SBD)', 'iso_code' => 'SBD'],
                                ['name' => 'Sri Lankan Rupees (LKR)', 'iso_code' => 'LKR'],
                                ['name' => 'Surinamese Dollar (SRD)', 'iso_code' => 'SRD'],
                                ['name' => 'Swazi Lilangeni (SZL)', 'iso_code' => 'SZL'],
                                ['name' => 'Swedish Kronor (SEK)', 'iso_code' => 'SEK'],
                                ['name' => 'Swiss Francs (CHF)', 'iso_code' => 'CHF'],
                                ['name' => 'Taiwan Dollars (TWD)', 'iso_code' => 'TWD'],
                                ['name' => 'Thai baht (THB)', 'iso_code' => 'THB'],
                                ['name' => 'Tanzanian Shilling (TZS)', 'iso_code' => 'TZS'],
                                ['name' => 'Trinidad and Tobago Dollars (TTD)', 'iso_code' => 'TTD'],
                                ['name' => 'Tunisian Dinar (TND)', 'iso_code' => 'TND'],
                                ['name' => 'Turkish Lira (TRY)', 'iso_code' => 'TRY'],
                                ['name' => 'Turkmenistani Manat (TMT)', 'iso_code' => 'TMT'],
                                ['name' => 'Ugandan Shilling (UGX)', 'iso_code' => 'UGX'],
                                ['name' => 'Ukrainian Hryvnia (UAH)', 'iso_code' => 'UAH'],
                                ['name' => 'United Arab Emirates Dirham (AED)', 'iso_code' => 'AED'],
                                ['name' => 'Uruguayan Pesos (UYU)', 'iso_code' => 'UYU'],
                                ['name' => 'Uzbekistan som (UZS)', 'iso_code' => 'UZS'],
                                ['name' => 'Vanuatu Vatu (VUV)', 'iso_code' => 'VUV'],
                                ['name' => 'Venezuelan Bolivares (VEF)', 'iso_code' => 'VEF'],
                                ['name' => 'Vietnamese đồng (VND)', 'iso_code' => 'VND'],
                                ['name' => 'West African CFA franc (XOF)', 'iso_code' => 'XOF'],
                                ['name' => 'Yemeni Rial (YER)', 'iso_code' => 'YER'],
                                ['name' => 'Zambian Kwacha (ZMW)', 'iso_code' => 'ZMW'],
                              ]); 
        
        foreach($currencies as $currency) {
            Currency::create([ 
                'name' => $currency['name'],
                'iso_code' => $currency['iso_code']
            ]);
        }
    }
}
